# Generated by Django 2.2.2 on 2020-11-29 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_site', '0003_auto_20201129_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetlike',
            old_name='tweet',
            new_name='spirit',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='spirit_user', through='social_site.TweetLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
